import { contextBridge, ipcRenderer } from 'electron';

const api = {
  persons: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('persons:create', data),
    get: (id: string) => ipcRenderer.invoke('persons:get', id),
    list: () => ipcRenderer.invoke('persons:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('persons:delete', id),
    search: (query: string) => ipcRenderer.invoke('persons:search', query),
    addName: (personId: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:addName', personId, data),
    getNames: (personId: string) => ipcRenderer.invoke('persons:getNames', personId),
    updateName: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:updateName', id, data),
    deleteName: (id: string) => ipcRenderer.invoke('persons:deleteName', id),
    addIdentifier: (personId: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:addIdentifier', personId, data),
    getIdentifiers: (personId: string) => ipcRenderer.invoke('persons:getIdentifiers', personId),
    deleteIdentifier: (id: string) => ipcRenderer.invoke('persons:deleteIdentifier', id),
  },
  relationships: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('relationships:create', data),
    get: (id: string) => ipcRenderer.invoke('relationships:get', id),
    list: () => ipcRenderer.invoke('relationships:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('relationships:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('relationships:delete', id),
    getForPerson: (personId: string) => ipcRenderer.invoke('relationships:getForPerson', personId),
    search: (query: string) => ipcRenderer.invoke('relationships:search', query),
  },
  eventParticipants: {
    add: (data: Record<string, unknown>) => ipcRenderer.invoke('eventParticipants:add', data),
    getForEvent: (eventId: string) => ipcRenderer.invoke('eventParticipants:getForEvent', eventId),
    remove: (id: string) => ipcRenderer.invoke('eventParticipants:remove', id),
  },
  events: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('events:create', data),
    get: (id: string) => ipcRenderer.invoke('events:get', id),
    forPerson: (personId: string) => ipcRenderer.invoke('events:forPerson', personId),
    forRelationship: (relationshipId: string) => ipcRenderer.invoke('events:forRelationship', relationshipId),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('events:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('events:delete', id),
  },
  sources: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('sources:create', data),
    get: (id: string) => ipcRenderer.invoke('sources:get', id),
    list: () => ipcRenderer.invoke('sources:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('sources:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('sources:delete', id),
    search: (query: string) => ipcRenderer.invoke('sources:search', query),
  },
  citations: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('citations:create', data),
    get: (id: string) => ipcRenderer.invoke('citations:get', id),
    forSource: (sourceId: string) => ipcRenderer.invoke('citations:forSource', sourceId),
    forEvent: (eventId: string) => ipcRenderer.invoke('citations:forEvent', eventId),
    forPerson: (personId: string) => ipcRenderer.invoke('citations:forPerson', personId),
    forRelationship: (relationshipId: string) => ipcRenderer.invoke('citations:forRelationship', relationshipId),
    forPlace: (placeId: string) => ipcRenderer.invoke('citations:forPlace', placeId),
    delete: (id: string) => ipcRenderer.invoke('citations:delete', id),
  },
  places: {
    create: (data: unknown) => ipcRenderer.invoke('places:create', data),
    get: (id: string) => ipcRenderer.invoke('places:get', id),
    list: () => ipcRenderer.invoke('places:list'),
    search: (query: string) => ipcRenderer.invoke('places:search', query),
    update: (id: string, data: unknown) => ipcRenderer.invoke('places:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('places:delete', id),
    findOrCreate: (name: string) => ipcRenderer.invoke('places:findOrCreate', name),
  },
};

contextBridge.exposeInMainWorld('api', api);
