import { contextBridge, ipcRenderer } from 'electron';

const api = {
  persons: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('persons:create', data),
    get: (id: string) => ipcRenderer.invoke('persons:get', id),
    list: () => ipcRenderer.invoke('persons:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('persons:delete', id),
    search: (query: string) => ipcRenderer.invoke('persons:search', query),
    addName: (personId: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:addName', personId, data),
    getNames: (personId: string) => ipcRenderer.invoke('persons:getNames', personId),
    updateName: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:updateName', id, data),
    deleteName: (id: string) => ipcRenderer.invoke('persons:deleteName', id),
    addIdentifier: (personId: string, data: Record<string, unknown>) => ipcRenderer.invoke('persons:addIdentifier', personId, data),
    getIdentifiers: (personId: string) => ipcRenderer.invoke('persons:getIdentifiers', personId),
    deleteIdentifier: (id: string) => ipcRenderer.invoke('persons:deleteIdentifier', id),
  },
  relationships: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('relationships:create', data),
    get: (id: string) => ipcRenderer.invoke('relationships:get', id),
    list: () => ipcRenderer.invoke('relationships:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('relationships:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('relationships:delete', id),
    getForPerson: (personId: string) => ipcRenderer.invoke('relationships:getForPerson', personId),
    search: (query: string) => ipcRenderer.invoke('relationships:search', query),
  },
  eventParticipants: {
    add: (data: Record<string, unknown>) => ipcRenderer.invoke('eventParticipants:add', data),
    getForEvent: (eventId: string) => ipcRenderer.invoke('eventParticipants:getForEvent', eventId),
    remove: (id: string) => ipcRenderer.invoke('eventParticipants:remove', id),
  },
  events: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('events:create', data),
    get: (id: string) => ipcRenderer.invoke('events:get', id),
    forPerson: (personId: string) => ipcRenderer.invoke('events:forPerson', personId),
    forRelationship: (relationshipId: string) => ipcRenderer.invoke('events:forRelationship', relationshipId),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('events:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('events:delete', id),
  },
  sources: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('sources:create', data),
    get: (id: string) => ipcRenderer.invoke('sources:get', id),
    list: () => ipcRenderer.invoke('sources:list'),
    update: (id: string, data: Record<string, unknown>) => ipcRenderer.invoke('sources:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('sources:delete', id),
    search: (query: string) => ipcRenderer.invoke('sources:search', query),
  },
  citations: {
    create: (data: Record<string, unknown>) => ipcRenderer.invoke('citations:create', data),
    get: (id: string) => ipcRenderer.invoke('citations:get', id),
    forSource: (sourceId: string) => ipcRenderer.invoke('citations:forSource', sourceId),
    forEvent: (eventId: string) => ipcRenderer.invoke('citations:forEvent', eventId),
    forPerson: (personId: string) => ipcRenderer.invoke('citations:forPerson', personId),
    forRelationship: (relationshipId: string) => ipcRenderer.invoke('citations:forRelationship', relationshipId),
    forPlace: (placeId: string) => ipcRenderer.invoke('citations:forPlace', placeId),
    delete: (id: string) => ipcRenderer.invoke('citations:delete', id),
  },
  gedcom: {
    import: (opts?: unknown) => ipcRenderer.invoke('gedcom:import', opts),
    export: () => ipcRenderer.invoke('gedcom:export'),
  },
  import: {
    genneyCheckDocker: () => ipcRenderer.invoke('import:genneyCheckDocker'),
    genneySelectDerby: () => ipcRenderer.invoke('import:genneySelectDerby'),
    genneySelectArchive: () => ipcRenderer.invoke('import:genneySelectArchive'),
    genneyDiscover: (opts: unknown) => ipcRenderer.invoke('import:genneyDiscover', opts),
    genneyRun: (opts: unknown) => ipcRenderer.invoke('import:genneyRun', opts),
    onProgress: (cb: (msg: string) => void) => ipcRenderer.on('import:genneyProgress', (_e, data: { message: string }) => cb(data.message)),
  },
  db: {
    getCurrent: () => ipcRenderer.invoke('db:getCurrent'),
    getRecent: () => ipcRenderer.invoke('db:getRecent'),
    createNew: () => ipcRenderer.invoke('db:createNew'),
    openExisting: () => ipcRenderer.invoke('db:openExisting'),
    switchTo: (dbPath: string) => ipcRenderer.invoke('db:switchTo', dbPath),
    onSwitched: (cb: () => void) => ipcRenderer.on('db:switched', cb),
  },
  places: {
    create: (data: unknown) => ipcRenderer.invoke('places:create', data),
    get: (id: string) => ipcRenderer.invoke('places:get', id),
    list: () => ipcRenderer.invoke('places:list'),
    search: (query: string) => ipcRenderer.invoke('places:search', query),
    update: (id: string, data: unknown) => ipcRenderer.invoke('places:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('places:delete', id),
    findOrCreate: (name: string) => ipcRenderer.invoke('places:findOrCreate', name),
    getPath: (id: string) => ipcRenderer.invoke('places:getPath', id),
  },
  groups: {
    list: () => ipcRenderer.invoke('groups:list'),
    get: (id: string) => ipcRenderer.invoke('groups:get', id),
    create: (data: unknown) => ipcRenderer.invoke('groups:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('groups:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('groups:delete', id),
    addMember: (groupId: string, personId: string) => ipcRenderer.invoke('groups:addMember', groupId, personId),
    removeMember: (groupId: string, personId: string) => ipcRenderer.invoke('groups:removeMember', groupId, personId),
    getMembers: (groupId: string) => ipcRenderer.invoke('groups:getMembers', groupId),
    forPerson: (personId: string) => ipcRenderer.invoke('groups:forPerson', personId),
  },
  repositories: {
    list: () => ipcRenderer.invoke('repositories:list'),
    get: (id: string) => ipcRenderer.invoke('repositories:get', id),
    create: (data: unknown) => ipcRenderer.invoke('repositories:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('repositories:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('repositories:delete', id),
    forSource: (sourceId: string) => ipcRenderer.invoke('repositories:forSource', sourceId),
    linkSource: (sourceId: string, repoId: string) => ipcRenderer.invoke('repositories:linkSource', sourceId, repoId),
    unlinkSource: (sourceId: string, repoId: string) => ipcRenderer.invoke('repositories:unlinkSource', sourceId, repoId),
  },
  researchTasks: {
    list: () => ipcRenderer.invoke('researchTasks:list'),
    get: (id: string) => ipcRenderer.invoke('researchTasks:get', id),
    forPerson: (personId: string) => ipcRenderer.invoke('researchTasks:forPerson', personId),
    create: (data: unknown) => ipcRenderer.invoke('researchTasks:create', data),
    update: (id: string, data: unknown) => ipcRenderer.invoke('researchTasks:update', id, data),
    delete: (id: string) => ipcRenderer.invoke('researchTasks:delete', id),
  },
  checks: {
    runAll: () => ipcRenderer.invoke('checks:runAll'),
    forPerson: (personId: string) => ipcRenderer.invoke('checks:forPerson', personId),
  },
  media: {
    list: () => ipcRenderer.invoke('media:list'),
    get: (id: string) => ipcRenderer.invoke('media:get', id),
    create: (data: unknown) => ipcRenderer.invoke('media:create', data),
    delete: (id: string) => ipcRenderer.invoke('media:delete', id),
    forEntity: (entityType: string, entityId: string) => ipcRenderer.invoke('media:forEntity', entityType, entityId),
    addLink: (data: unknown) => ipcRenderer.invoke('media:addLink', data),
    removeLink: (linkId: string) => ipcRenderer.invoke('media:removeLink', linkId),
  },
  print: {
    print: () => ipcRenderer.invoke('print:print'),
    exportPdf: (path?: string) => ipcRenderer.invoke('print:exportPdf', path),
  },
};

contextBridge.exposeInMainWorld('api', api);
