import type { LinkRule } from '../source-linker';

export const enRules: LinkRule[] = [
  {
    id: 'familysearch-ark',
    name: 'FamilySearch ARK',
    pattern: 'ark:/61903/([^\\s,;)]+)',
    urlTemplate: 'https://www.familysearch.org/ark:/61903/$1',
    example: 'ark:/61903/1:1:XHLN-69H',
    locale: 'en',
    enabled: true,
    priority: 10,
  },
  {
    id: 'findagrave',
    name: 'FindAGrave Memorial',
    pattern: 'Find\\s*[Aa]\\s*Grave[^0-9]*(\\d{5,})',
    urlTemplate: 'https://www.findagrave.com/memorial/$1',
    example: 'Find A Grave memorial 12345678',
    locale: 'en',
    enabled: true,
    priority: 20,
  },
  {
    id: 'ancestry-record',
    name: 'Ancestry Record',
    pattern: 'ancestry\\.com/discoveryui-content/view/(\\d+):(\\d+)',
    urlTemplate: 'https://www.ancestry.com/discoveryui-content/view/$1:$2',
    example: 'ancestry.com/discoveryui-content/view/12345:6789',
    locale: 'en',
    enabled: true,
    priority: 20,
  },
  {
    id: 'familysearch-film',
    name: 'FamilySearch Film',
    pattern: '[Ff]ilm\\s*#?\\s*(\\d{6,})',
    urlTemplate: 'https://www.familysearch.org/search/film/$1',
    example: 'Film #1234567',
    locale: 'en',
    enabled: true,
    priority: 30,
  },
  {
    id: 'myheritage-record',
    name: 'MyHeritage Record',
    pattern: 'myheritage\\.com/research/record-(\\d+-\\d+)',
    urlTemplate: 'https://www.myheritage.com/research/record-$1',
    example: 'myheritage.com/research/record-1-300123456',
    locale: 'en',
    enabled: true,
    priority: 20,
  },
  {
    id: 'geni-profile',
    name: 'Geni Profile',
    pattern: 'geni\\.com/people/[^/]+/(\\d+)',
    urlTemplate: 'https://www.geni.com/people/profile/$1',
    example: 'geni.com/people/John-Smith/6000000012345678',
    locale: 'en',
    enabled: true,
    priority: 20,
  },
  {
    id: 'wikitree-id',
    name: 'WikiTree Profile',
    pattern: 'WikiTree:\\s*([A-Za-z]+-\\d+)',
    urlTemplate: 'https://www.wikitree.com/wiki/$1',
    example: 'WikiTree: Smith-12345',
    locale: 'en',
    enabled: true,
    priority: 20,
  },
  {
    id: 'billiongraves',
    name: 'BillionGraves',
    pattern: 'BillionGraves[^0-9]*(\\d{5,})',
    urlTemplate: 'https://billiongraves.com/grave/$1',
    example: 'BillionGraves memorial 1234567',
    locale: 'en',
    enabled: true,
    priority: 25,
  },
];
