import type { LinkRule } from '../source-linker';

export const svRules: LinkRule[] = [
  {
    id: 'arkivdigital-aid',
    name: 'ArkivDigital (AID)',
    pattern: 'AID:\\s*v(\\d+)\\.b(\\d+)(?:\\.s\\d+)?',
    urlTemplate: 'https://app.arkivdigital.se/volume/v$1?image=$2',
    example: 'AID: v170308.b530.s44',
    locale: 'sv',
    enabled: true,
    priority: 10,
  },
  {
    id: 'riksarkivet-nad',
    name: 'Riksarkivet (NAD)',
    pattern: 'NAD:\\s*(SE/[A-Za-z]+/\\d+)',
    urlTemplate: 'https://sok.riksarkivet.se/nad?postid=ArkisRef+$1',
    example: 'NAD: SE/VALA/00333',
    locale: 'sv',
    enabled: true,
    priority: 10,
  },
  {
    id: 'riksarkivet-bildvisning',
    name: 'Riksarkivet Image',
    pattern: 'sok\\.riksarkivet\\.se/bildvisning/([A-Z0-9_]+)',
    urlTemplate: 'https://sok.riksarkivet.se/bildvisning/$1',
    example: 'sok.riksarkivet.se/bildvisning/A0017414_00092',
    locale: 'sv',
    enabled: true,
    priority: 20,
  },
  {
    id: 'kyrkoarkiv',
    name: 'Kyrkoarkiv',
    pattern: '([A-ZÅÄÖ][a-zA-ZåäöéÅÄÖ\\d,\\s-]+?)\\s*\\([A-ZÅÄÖ][A-ZÅÄÖ,\\s]*\\)\\s+[A-Z]+[A-Za-z]*\\d*:\\d+[A-Za-z]*',
    urlTemplate: 'https://sok.riksarkivet.se/kyrkoarkiv?Arkivsok=$1&Sok=true',
    example: 'Alvesta (G) AI:6 (1813-1828)',
    locale: 'sv',
    enabled: true,
    priority: 15,
  },
  {
    id: 'generalmönsterrullor',
    name: 'Generalmönsterrullor',
    pattern: '(Generalmönsterrullor\\s*-\\s*[A-ZÅÄÖ][a-zA-ZåäöéÅÄÖ\\s]+?)\\s*\\([A-ZÅÄÖ][A-ZÅÄÖ,\\s]*\\)\\s+(\\d+)',
    urlTemplate: 'https://sok.riksarkivet.se/kyrkoarkiv?Arkivsok=$1&Sok=true',
    example: 'Generalmönsterrullor - Kalmar regemente (F, G, H) 416 (1802)',
    locale: 'sv',
    enabled: true,
    priority: 15,
  },
  {
    id: 'domstolsarkiv',
    name: 'Domstolsarkiv',
    pattern: '([A-ZÅÄÖ][a-zA-ZåäöéÅÄÖ\\d,\\s-]+?(?:domsaga|rådhusrätt|magistrat|fögderi|lasaretts?\\s+\\S+))\\s*\\([A-ZÅÄÖ][A-ZÅÄÖ,\\s]*\\)\\s+[A-Z]+[A-Za-z]*\\d*:\\d+',
    urlTemplate: 'https://sok.riksarkivet.se/kyrkoarkiv?Arkivsok=$1&Sok=true',
    example: 'Bråbygdens domsaga (E) FII:22 (1943-1944)',
    locale: 'sv',
    enabled: true,
    priority: 14,
  },
  {
    id: 'svbf',
    name: 'Sveriges Befolkning',
    pattern: 'SvBf\\d{4}|Sveriges [Bb]efolkning \\d{4}',
    urlTemplate: 'https://www.genealogi.se/',
    example: 'SvBf1980',
    locale: 'sv',
    enabled: true,
    priority: 50,
  },
];
