import type { LinkRule } from '../source-linker';

export const svRules: LinkRule[] = [
  {
    id: 'arkivdigital-aid',
    name: 'ArkivDigital (AID)',
    pattern: 'AID:\\s*v(\\d+)\\.b(\\d+)(?:\\.s\\d+)?',
    urlTemplate: 'https://app.arkivdigital.se/volume/v$1?image=$2',
    example: 'AID: v170308.b530.s44',
    locale: 'sv',
    enabled: true,
    priority: 10,
  },
  {
    id: 'riksarkivet-nad',
    name: 'Riksarkivet (NAD)',
    pattern: 'NAD:\\s*(SE/[A-Za-z]+/\\d+)',
    urlTemplate: 'https://sok.riksarkivet.se/nad?postid=ArkisRef+$1',
    example: 'NAD: SE/VALA/00333',
    locale: 'sv',
    enabled: true,
    priority: 10,
  },
  {
    id: 'riksarkivet-bildvisning',
    name: 'Riksarkivet Image',
    pattern: 'sok\\.riksarkivet\\.se/bildvisning/([A-Z0-9_]+)',
    urlTemplate: 'https://sok.riksarkivet.se/bildvisning/$1',
    example: 'sok.riksarkivet.se/bildvisning/A0017414_00092',
    locale: 'sv',
    enabled: true,
    priority: 20,
  },
  {
    id: 'riksarkivet-kyrkoarkiv',
    name: 'Riksarkivet Kyrkoarkiv',
    pattern: '([A-ZÅÄÖ][a-zåäöé]+(?:\\s[a-zåäö]+)*)\\s*\\([A-ZÅÄÖ,\\s]+\\)\\s*[A-Z]+[IVXa-z]*:\\d+',
    urlTemplate: 'https://sok.riksarkivet.se/kyrkoarkiv?Arkivsok=$1&Sok=true',
    example: 'Alvesta (G) AI:6 (1813-1828)',
    locale: 'sv',
    enabled: true,
    priority: 15,
  },
  {
    id: 'svbf',
    name: 'Sveriges Befolkning',
    pattern: 'SvBf\\d{4}|Sveriges [Bb]efolkning \\d{4}',
    urlTemplate: 'https://www.genealogi.se/',
    example: 'SvBf1980',
    locale: 'sv',
    enabled: true,
    priority: 50,
  },
];
